### ISSUE TITLE
Cannot run streamlit demo locally

### ISSUE THREAD

**Issue by ghosh-r** [arampacha/CLIP-rsicd#15]
I tried to run the demo using the instructions given in the markdown file in the `demo-1` directory as instructed by @sujitpal .

Did not get the context of-

> In addition, we need to generate CLIP vectors for the image corpus using demo-image-encoder.ipynb.

So, did not follow it.

I do the rest sequentially. This is what I get-

```bash
SSH: Attempting to connect to worker 0...
bind [127.0.0.1]:8501: Address already in use
channel_setup_fwd_listener_tcpip: cannot listen to port: 8501
Could not request local forwarding.
```

What is causing this? How to run this demo?

**Comment by ghosh-r** [comment]
After closing an already running server on the same port, when I try to SSH into the VM with SSL flag, I get this-

```bash
gcloud alpha compute tpus tpu-vm ssh fishtail --zone us-central1-a --project hf-flax --ssh-flag="-L 8501:localhost:8501"
ERROR: gcloud crashed (AttributeError): 'NoneType' object has no attribute 'split'
```

**Comment by sujitpal** [comment]
I moved the vectors file into a common location and updated the instructions and verified it running locally post these changes. BTW you need the additional packages (streamlit and nmslib) in your `jenv` environment to run this. Can you please pull the updates and try this again?

**Comment by sujitpal** [comment]
actually hold off a bit trying something else

**Comment by sujitpal** [comment]
ok done now

**Comment by sujitpal** [comment]
closing this since @arampacha and @goutham794 were both able to run locally.
