### ISSUE TITLE
**Data**

### ISSUE THREAD

**Issue by arampacha** [arampacha/CLIP-rsicd#2]
- [x] Upload RSICD to TPU-vm storage
 - [x] repack data into `Dataset`
 - [x] check other datasets
 - [x] prepare dataloaders

**Comment by devvidhani** [comment]
Uploaded datasets

RSICD
UCM
Sydney

with captions at

gs://clip_rsicd/rsicd_dataset/
gs://clip_rsicd/sydney_dataset/
gs://clip_rsicd/ucm/


                                 gs://clip_rsicd/ucm_dataset/
