### ISSUE TITLE
Find Eval Satellite data and figure out loading code.

### ISSUE THREAD

**Issue by sujitpal** [arampacha/CLIP-rsicd#3]

**Comment by sujitpal** [comment]
Found this dataset on Kaggle: [Dstl Satellite Imagery Feature Detection](https://www.kaggle.com/c/dstl-satellite-imagery-feature-detection/data?select=train_geojson_v3.zip) contains 450 images in 10 classes.

1. __Buildings__ - large building, residential, non-residential, fuel storage facility, fortified building
2. __Misc. Manmade structures__
3. __Road__
4. __Track__ - poor/dirt/cart track, footpath/trail
5. __Trees__ - woodland, hedgerows, groups of trees, standalone trees
6. __Crops__ - contour ploughing/cropland, grain (wheat) crops, row (potatoes, turnips) crops
7. __Waterway__
8. __Standing water__
9. __Vehicle Large__ - large vehicle (e.g. lorry, truck,bus), logistics vehicle
10. __Vehicle Small__ - small vehicle (car, van), motorbike

**Comment by sujitpal** [comment]
Does not look very usable unfortunately.

* TIF images are provided as 3-band RGB and 16-band versions. 3-band ones don't render very well, there is some information that says to use specific bands of the 16-band images to render more natural RGB images but I haven't tried that. In any case, the numbers in the TIF files are reflectances and not pixel intensities so it may not be directly transferable anyway. So these may not be good candidates for test images for a CLIP model trained on photo-realistic satellite images such as RSICD. 
* There are only 25 labeled images out of the 450. Each labeled image has multiple annotations (1 or more of 10 class types) associated with specific polygons in the image. So we could build bounding boxes out of the polygons and mask out the rest to create a larger dataset out of patches for evaluation. However, from some experiments the polygons are very small and not really usable for masking and patching.

I think we should consider setting aside a portion of the RSICD dataset for evaluation and augment the rest. I am going to close this as wontfix for reasons above.

**Comment by devvidhani** [comment]
@sujitpal -- copied the data on google drive. See comment in https://github.com/arampacha/CLIP-rsicd/issues/2

**Comment by sujitpal** [comment]
I got an idea to get around the issues and to use the 16 channel version, I have checked in the notebook  for this -- https://github.com/arampacha/CLIP-rsicd/blob/master/dstl-dataset-explore.ipynb . Still probably not exactly similar to provided RSICD images, but can be made closer. Anyway we can revisit if we want to do this later.
