### ISSUE TITLE
Getting erro while Using this script to fine tune(Urgent)

### ISSUE THREAD

**Issue by minakshimathpal** [arampacha/CLIP-rsicd#33]
@arampacha I am getting this error while executing ImageTextDataset
![image](https://user-images.githubusercontent.com/61991627/154367415-bd484761-a614-41cc-b3ad-60106acfa97c.png)
Please help

**Comment by arampacha** [comment]
Hi! This error is most likely caused by empty `filepaths` list. The `root` folder should contain jsonl files named following certain pattern, for example "train.jsonl". Example files (with augmented captions) can be found in data folder.
Thanks for the issue. I'll look at providing more informative error messages for this scenario

**Comment by minakshimathpal** [comment]
@arampacha thanks for the solution.....i have coco captions dataset in json format...is there any way to convert it into jsonl...i tried a script but couldn't fetch the captions..That script is writing images only.no captions..please help

**Comment by arampacha** [comment]
@minakshimathpal have a look at [RSICD_data notebook](https://github.com/arampacha/CLIP-rsicd/blob/master/nbs/RSICD_data.ipynb). There is `convert_dataset_json` function which converts `json` to `jsonl`. You might need to adapt it to your case if some of the keys mismatch.

**Comment by INF800** [comment]
> Hi! This error is most likely caused by empty `filepaths` list. The `root` folder should contain jsonl files named following certain pattern, for example "train.jsonl". Example files (with augmented captions) can be found in data folder. Thanks for the issue. I'll look at providing more informative error messages for this scenario

Unfortuantely, it occurs even if data folder is not empty in my case (tried both with relative and absolute paths). Can't get around it. Reproduced the issue here in colab: https://colab.research.google.com/github/INF800/CLIP-rsicd/blob/master/nbs/Finetuning_CLIP_with_HF_and_jax.ipynb

**Comment by INF800** [comment]
To reproduce, just run all the cell of above notebook. It will terminate with same error. Note the cell `!ls {data_args.data_dir}` which verifies that folder is not empty.

```
rsicd_images		  textaug_train_rsicd.jsonl
textaug_test_rsicd.jsonl  textaug_valid_rsicd.jsonl
```

**Comment by arampacha** [comment]
Hi @INF800! Thanks for reproducer. I've just pushed a fix. Could you sync your fork and check if it works now?

**Comment by rozeappletree** [comment]
Sure. Thanks! What was the issue BTW.

**Comment by arampacha** [comment]
I've actually broke the dataset creation in stupid way when adding check for empty `filepaths` list in heist.
Exhausted the generator at check lol. Should've postpone pushing till weekend and test it obviously, my bad. Thanks again for turning attention to this.

**Comment by arampacha** [comment]
Looks like now everything works as expected, so I'll close the issue. Feel free to ping me if anything
