### ISSUE TITLE
Image encoding with clip-rscidv2 and  clip-rscidv2 transformer doesn't work

### ISSUE THREAD

**Issue by Pinneaple** [arampacha/CLIP-rsicd#38]
Hello,

I would like to encode an image and a text separately into a vector using clip-rscid-v2 and save them into a nearest neighbor library. What will be the best approach to encode an image? I would like to replicate the model.encode_image(image) from the origin clip model. Also, process = CLIPProcessor.from_pretrained("flax-community/clip-rsicd-v2") does not work.

Thanks

**Comment by arampacha** [comment]
Hello, thanks for opening an issue.

It looks like we need to add files for fast tokenizer to make it work with latest version of transformers. For now you can load the processor as follows:
```py
processor = CLIPProcessor.from_pretrained(model_id, from_slow=True)
```
or alternatively load processor from "openai/clip*" (it is identical)

The image embeddings can be computed as follows:
```py
from transformers import CLIPVisionModel

vision_model = CLIPVisionModel.from_pretrained(model_id)
image_embeddings = vision_model(pixel_values=inputs["pixel_values"])["pooler_output"]
```
Or equivalently using `clip_model.vision_model` module.
I agree it would be useful to have corresponding `encode_image` and `encode_text` methods for the main CLIPmodel class :+1:

I'll keep the issue open before we update files to work without `from_slow` flag.
Feel free to ping me if the above doesn't work for you

**Comment by arampacha** [comment]
Linked models are updated to for compatibility with latest transformers version, processor can be loaded using  `CLIPProcessor.from_pretrained(model_id)` without an error. Thanks for opening an issue @Pinneaple . Hope your questions has been answered
