### ISSUE TITLE
Remote sensing image captioning

### ISSUE THREAD

**Issue by Waiting-TT** [arampacha/CLIP-rsicd#39]
Thanks for your excellent work! This pretraining work is done on three RSICD and how can the code directly be used to generate captions on these RSICD? Could you please give me some instructions? thanks a lot again!

**Comment by arampacha** [comment]
Hello. Thanks for your interest. The CLIP model cannot be used to generate captions directly. We have plans to add a finetuned prefix GPT or similar model at some point for captioning. But there is no ETA for it as of now. You can try out the approach described here https://github.com/rmokady/CLIP_prefix_caption.

**Comment by Waiting-TT** [comment]
Thanks for your reply!

从 Windows 版邮件发送

发件人: arampacha
发送时间: 2022年5月14日 22:09
收件人: arampacha/CLIP-rsicd
抄送: Waiting-TT; Author
主题: Re: [arampacha/CLIP-rsicd] Remote sensing image captioning (Issue#39)

Hello. Thanks for your interest. The CLIP model cannot be used to generate captions directly. We have plans to add a finetuned prefix GPT or similar model at some point for captioning. But there is no ETA for it as of now. You can try out the approach described here https://github.com/rmokady/CLIP_prefix_caption.
